const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let blocks=[], insertIndex=0, sourceName='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const strip=s=>String(s??'').replace(/\\([~*])/g,'$1');
function inline(s){return esc(strip(s)).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/\n/g,'<br>')}
function parseTable(lines){return {type:'table',rows:lines.filter((_,i)=>i!==1).map(l=>l.trim().replace(/^\||\|$/g,'').split('|').map(x=>strip(x.trim()).replace(/^\*\*|\*\*$/g,'')))}}
function parseMarkdown(md){
  const lines=md.replace(/^\uFEFF/,'').replace(/\r/g,'').split('\n'),out=[];let pendingImage='',i=0;
  while(i<lines.length){let line=lines[i].trim();if(!line){i++;continue}
    const img=line.match(/^!?(?:\[image\]|!\[[^\]]*\])\((https?:\/\/[^)]+)\)$/i);if(img){pendingImage=img[1];i++;continue}
    const speaker=line.match(/^\*\*([^*\n]+?):\*\*\s*(.*)$/);if(speaker){let body=speaker[2],j=i+1;while(j<lines.length){const n=lines[j],t=n.trim();if(!t){if(body&&!body.endsWith('\n'))body+='\n';j++;continue}if(/^\[image\]\(/.test(t)||/^\*\*[^*]+?:\*\*/.test(t)||/^\*\*\*/.test(t)||/^\|/.test(t))break;body+=(body?'\n':'')+n;j++}out.push({type:'speech',speaker:strip(speaker[1]),body:strip(body.trim()),avatar:pendingImage});pendingImage='';i=j;continue}
    if(/^\|/.test(line)&&i+1<lines.length&&/^\|?\s*:?-+/.test(lines[i+1].trim())){let rows=[lines[i]],j=i+1;while(j<lines.length&&/^\|/.test(lines[j].trim()))rows.push(lines[j++]);out.push(parseTable(rows));i=j;continue}
    const narration=line.match(/^\*\*\*(.*?)\*\*\*$/);if(narration){let text=strip(narration[1]),j=i+1;while(j<lines.length){const m=lines[j].trim().match(/^\*\*\*(.*?)\*\*\*$/);if(!m)break;text+='\n'+strip(m[1]);j++;while(j<lines.length&&!lines[j].trim())j++}out.push({type:'narration',body:text});i=j;continue}
    if(pendingImage){out.push({type:'contentImage',src:pendingImage,alt:'삽입 이미지'});pendingImage=''}
    let raw=line,j=i+1;while(j<lines.length&&lines[j].trim()&&!/^\[image\]\(/.test(lines[j].trim())&&!/^\*\*[^*]+?:\*\*/.test(lines[j].trim())&&!/^\*\*\*/.test(lines[j].trim())&&!/^\|/.test(lines[j].trim()))raw+='\n'+lines[j++];out.push({type:'raw',body:strip(raw)});i=j
  }
  if(pendingImage)out.push({type:'contentImage',src:pendingImage,alt:'삽입 이미지'});return out
}
function initials(name){return name.trim().slice(0,1)||'?'}
function blockHtml(b,index,editing=true){let h='';if(b.type==='speech')h=`<article class="speech">${b.avatar?`<img class="avatar" src="${esc(b.avatar)}" alt="${esc(b.speaker)} 인장">`:`<span class="avatar placeholder">${esc(initials(b.speaker))}</span>`}<div><div class="speaker">${esc(b.speaker)}</div><div class="speech-body">${inline(b.body)}</div></div></article>`;if(b.type==='narration')h=`<div class="narration">${inline(b.body)}</div>`;if(b.type==='table')h=`<table class="roll-table"><tbody>${b.rows.map((r,ri)=>`<tr>${r.map(c=>ri===0?`<th>${inline(c)}</th>`:`<td>${inline(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;if(b.type==='raw')h=`<div class="raw">${inline(b.body)}</div>`;if(b.type==='contentImage')h=`<div class="handout"><div class="handout-body"><img src="${esc(b.src)}" alt="${esc(b.alt)}"></div></div>`;if(b.type==='handout')h=`<article class="handout"><div class="handout-head"><strong>${esc(b.title)}</strong><span class="handout-kind">HANDOUT</span></div><div class="handout-body">${b.mode==='image'?`<img src="${esc(b.data)}" alt="${esc(b.title)}">`:inline(b.body)}</div></article>`;return editing?`<div class="block" data-index="${index}">${h}<div class="block-actions"><button data-move="up" title="위로">↑</button><button data-delete title="삭제">삭제</button><button data-move="down" title="아래로">↓</button></div></div>`:h}
function render(){const t=$('#timeline');t.innerHTML=blocks.map((b,i)=>`<div class="insert-slot"><button data-insert="${i}">+ 핸드아웃</button></div>${blockHtml(b,i)}`).join('')+`<div class="insert-slot"><button data-insert="${blocks.length}">+ 핸드아웃</button></div>`;const people=new Set(blocks.filter(x=>x.type==='speech').map(x=>x.speaker));$('#message-count').textContent=`항목 ${blocks.length}개`;$('#character-count').textContent=`등장인물 ${people.size}명`;$('#handout-count').textContent=`핸드아웃 ${blocks.filter(x=>x.type==='handout').length}개`;$$('[data-insert]').forEach(x=>x.onclick=()=>openHandout(+x.dataset.insert));$$('[data-delete]').forEach(x=>x.onclick=()=>{blocks.splice(+x.closest('.block').dataset.index,1);render()});$$('[data-move]').forEach(x=>x.onclick=()=>{const i=+x.closest('.block').dataset.index,j=x.dataset.move==='up'?i-1:i+1;if(j<0||j>=blocks.length)return;[blocks[i],blocks[j]]=[blocks[j],blocks[i]];render()})}
function importText(text,name=''){if(!text.trim())return fail('불러올 마크다운 내용이 없어요.');blocks=parseMarkdown(text);if(!blocks.length)return fail('변환할 수 있는 채팅 내용을 찾지 못했어요.');sourceName=name;const guessed=name.replace(/\.(md|markdown|txt)$/i,'')||'롤20 세션 로그';$('#title-input').value=$('#session-title').value.trim()||guessed;$('#import-view').hidden=true;$('#editor-view').hidden=false;render();scrollTo(0,0)}
function fail(msg){$('#import-error').textContent=msg;$('#import-error').hidden=false}
function readFile(file){if(!file)return;const r=new FileReader();r.onload=()=>importText(r.result,file.name);r.onerror=()=>fail('파일을 읽지 못했어요.');r.readAsText(file)}
const drop=$('#dropzone');
drop.onclick=()=>$('#file-input').click();
drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('#file-input').click()}};
$('#file-input').onchange=e=>readFile(e.target.files[0]);
['dragenter','dragover'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add('drag')}));
['dragleave','drop'].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove('drag')}));
drop.addEventListener('drop',e=>readFile(e.dataTransfer.files[0]));
document.addEventListener('paste',e=>{
  if(!$('#import-view').hidden&&document.activeElement!==$('#paste-input')){
    const f=[...e.clipboardData.files].find(x=>/\.(md|markdown|txt)$/i.test(x.name));
    if(f){e.preventDefault();readFile(f)}
  }
});
$('#convert-button').onclick=()=>importText($('#paste-input').value);
function openHandout(i){insertIndex=i;$('#handout-form').reset();$('#image-name').textContent='이미지를 선택하세요';$('#text-field').hidden=false;$('#image-field').hidden=true;$('#handout-dialog').showModal()}$('#handout-type').onchange=e=>{$('#text-field').hidden=e.target.value!=='text';$('#image-field').hidden=e.target.value!=='image'};$('#handout-image').onchange=e=>$('#image-name').textContent=e.target.files[0]?.name||'이미지를 선택하세요';$('#add-handout').onclick=e=>{e.preventDefault();const title=$('#handout-title').value.trim(),mode=$('#handout-type').value;if(!title)return $('#handout-title').reportValidity();if(mode==='text'){blocks.splice(insertIndex,0,{type:'handout',mode,title,body:$('#handout-body').value});finish()}else{const f=$('#handout-image').files[0];if(!f)return toast('이미지를 선택해주세요.');const r=new FileReader();r.onload=()=>{blocks.splice(insertIndex,0,{type:'handout',mode,title,data:r.result});finish()};r.readAsDataURL(f)}function finish(){$('#handout-dialog').close();render()}}
function documentHtml(data,title){const content=data.map((b,i)=>blockHtml(b,i,false)).join('');return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>:root{--ink:#1c1b19;--paper:#eeeae1;--sheet:#fffdf8;--muted:#746f66;--line:#d6d0c4}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.7 Pretendard,"Noto Sans KR",system-ui,sans-serif}header{padding:56px 24px 44px;text-align:center;border-bottom:1px solid var(--line);background:var(--sheet)}h1{font:700 clamp(34px,7vw,58px)/1.15 Georgia,"Noto Serif KR",serif;margin:0}header p{color:var(--muted);margin:10px 0 0}.log{width:min(820px,calc(100% - 30px));margin:35px auto 80px}.speech{display:grid;grid-template-columns:54px 1fr;gap:13px;padding:15px 18px;background:var(--sheet);border:1px solid var(--line);margin:9px 0;border-radius:4px}.avatar{width:54px;height:54px;border-radius:50%;object-fit:cover;background:#ddd7cc}.avatar.placeholder{display:grid;place-items:center;color:#8c8478;font-weight:700}.speaker{font-weight:800;margin-bottom:3px}.speech-body{white-space:pre-wrap;overflow-wrap:anywhere}.narration{font-family:Georgia,"Noto Serif KR",serif;text-align:center;padding:11px 30px;color:#514c45;font-style:italic}.roll-table{margin:14px auto;border-collapse:collapse;background:var(--sheet);min-width:380px}.roll-table td,.roll-table th{border:1px solid var(--line);padding:7px 12px}.handout{border:1px solid #3e3932;background:var(--sheet);margin:28px 0;box-shadow:7px 7px 0 #d9d0bf}.handout-head{padding:11px 15px;background:var(--ink);color:white;display:flex;justify-content:space-between}.handout-kind{font:700 11px ui-monospace;color:#d9c28e}.handout-body{padding:20px;white-space:pre-wrap}.handout img{display:block;max-width:100%;max-height:75vh;margin:auto}.raw{white-space:pre-wrap;padding:9px 16px;color:#555}@media(max-width:600px){.speech{grid-template-columns:42px 1fr;padding:12px}.avatar{width:42px;height:42px}.roll-table{min-width:0;width:100%}}</style></head><body><header><h1>${esc(title)}</h1><p>Roll20 session archive</p></header><main class="log">${content}</main></body></html>`}
async function embedAvatars(data){const copy=structuredClone(data),urls=[...new Set(copy.filter(x=>x.type==='speech'&&x.avatar&&!x.avatar.startsWith('data:')).map(x=>x.avatar))];if(!urls.length)return copy;$('#image-status').hidden=false;let ok=0;for(let i=0;i<urls.length;i++){const url=urls[i];$('#image-status').textContent=`인장을 HTML 안에 저장하는 중… ${i+1}/${urls.length}`;try{const res=await fetch(url);if(!res.ok)throw 0;const blob=await res.blob(),dataUrl=await new Promise((yes,no)=>{const r=new FileReader();r.onload=()=>yes(r.result);r.onerror=no;r.readAsDataURL(blob)});copy.forEach(x=>{if(x.avatar===url)x.avatar=dataUrl});ok++}catch{}}$('#image-status').textContent=ok===urls.length?`인장 ${ok}개를 HTML 안에 저장했어요.`:`인장 ${ok}/${urls.length}개를 저장했어요. 나머지는 원본 링크로 유지됩니다.`;return copy}
async function makeHtml(){const data=$('#embed-images').checked?await embedAvatars(blocks):structuredClone(blocks);return documentHtml(data,$('#title-input').value.trim()||'롤20 세션 로그')}
$('#preview-button').onclick=async()=>{const html=await makeHtml(),blob=new Blob([html],{type:'text/html'});$('#preview-frame').src=URL.createObjectURL(blob);$('#preview-dialog').showModal()};$('#download-button').onclick=async()=>{const html=await makeHtml(),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const title=$('#title-input').value.trim()||'롤20_세션_로그';a.download=title.replace(/[\\/:*?"<>|]/g,'_')+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);toast('HTML 파일을 저장했어요.')};$('#reset-button').onclick=()=>{if(!confirm('현재 편집 내용을 닫고 다른 파일을 불러올까요?'))return;blocks=[];$('#editor-view').hidden=true;$('#import-view').hidden=false;$('#file-input').value='';$('#paste-input').value='';scrollTo(0,0)};
function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,2500)}
